import { chromium } from "playwright-core";
import { homedir } from "node:os"; import { join } from "node:path";
process.env.LD_LIBRARY_PATH = `${join(homedir(),".local","lib","agent-board")}:${process.env.LD_LIBRARY_PATH||""}`;
let pass=0,fail=0; const chk=(n,c,d="")=>{c?(pass++,console.log("  PASS",n)):(fail++,console.log("  FAIL",n,d));};
const b=await chromium.launch({headless:true});
const ctx=await b.newContext({viewport:{width:1440,height:900}});
const p=await ctx.newPage();
p.on("pageerror", e=>console.log("PAGEERROR",String(e).slice(0,200)));
await p.goto("http://127.0.0.1:8792",{waitUntil:"domcontentloaded"});
await p.waitForTimeout(1200);
if(await p.getByLabel("board password").count()){await p.getByLabel("board password").fill("board-test-pw");await p.getByRole("button",{name:"Sign in"}).click();}
await p.locator('[aria-label^="column "]').first().waitFor({timeout:15000});
await p.locator('[aria-label="agent opencode-coding"]').click();
await p.locator('[aria-label^="agent panel"]').waitFor({timeout:8000});
await p.waitForTimeout(3500);
const sc = p.locator('[data-testid="chat-scroll"]');
chk("chat scroller", (await sc.count())>0);
chk("bubbles render", (await p.locator('.bubble').count())>0, String(await p.locator('.bubble').count()));
const atBottom = await sc.evaluate((el)=> el.scrollHeight - el.scrollTop - el.clientHeight < 40);
chk("pinned to bottom", atBottom);
console.log("  bubbles:", await p.locator('.bubble').count(), "tools:", await p.locator('.tool').count());
await p.screenshot({path:"/tmp/opencode/chat-rich.png",fullPage:true});
await b.close();
console.log(`\nCHAT-RICH: ${pass} passed, ${fail} failed`);
process.exit(fail?1:0);
