import { chromium } from "playwright-core";
import { homedir } from "node:os"; import { join } from "node:path";
process.env.LD_LIBRARY_PATH = `${join(homedir(),".local","lib","agent-board")}:${process.env.LD_LIBRARY_PATH||""}`;
let pass=0,fail=0; const chk=(n,c,d="")=>{c?(pass++,console.log("  PASS",n)):(fail++,console.log("  FAIL",n,d));};
const b=await chromium.launch({headless:true});
const ctx=await b.newContext({viewport:{width:1440,height:900}});
const p=await ctx.newPage();
p.on("pageerror", e=>console.log("PAGEERROR",String(e).slice(0,200)));
await p.goto("http://127.0.0.1:8792",{waitUntil:"domcontentloaded"});
await p.waitForTimeout(1200);
if(await p.getByLabel("board password").count()){await p.getByLabel("board password").fill("board-test-pw");await p.getByRole("button",{name:"Sign in"}).click();}
await p.locator('[aria-label^="column "]').first().waitFor({timeout:15000});
await p.locator('[aria-label="agent opencode-coding"]').click();
await p.locator('[aria-label^="agent panel"]').waitFor({timeout:8000});
await p.waitForTimeout(1500);
const box = p.getByLabel(/^Message /);
chk("composer present", (await box.count())>0);
await box.fill("/");
await p.waitForTimeout(1800);
const opts = await p.locator('.mantine-Combobox-option').count();
chk("slash commands suggest", opts>0, String(opts));
if (opts) console.log("  first:", (await p.locator('.mantine-Combobox-option').first().innerText()).replace(/\n/g," ").slice(0,50));
await box.fill("@");
await p.waitForTimeout(1800);
const opts2 = await p.locator('.mantine-Combobox-option').count();
chk("file suggest", opts2>0, String(opts2));
await box.fill("!");
await p.waitForTimeout(400);
chk("bash badge shows", (await p.locator('.shell-badge').count())>0);
await box.fill("");
await b.close();
console.log(`\nCOMPOSER2: ${pass} passed, ${fail} failed`);
process.exit(fail?1:0);
