import { chromium } from "playwright-core";
import { homedir } from "node:os"; import { join } from "node:path";
process.env.LD_LIBRARY_PATH = `${join(homedir(),".local","lib","agent-board")}:${process.env.LD_LIBRARY_PATH||""}`;
let pass=0,fail=0; const chk=(n,c,d="")=>{c?(pass++,console.log("  PASS",n)):(fail++,console.log("  FAIL",n,d));};
const b=await chromium.launch({headless:true});
const ctx=await b.newContext({viewport:{width:1440,height:900}});
const p=await ctx.newPage();
p.on("pageerror", e=>console.log("PAGEERROR",String(e).slice(0,200)));
await p.goto("http://127.0.0.1:8792",{waitUntil:"domcontentloaded"});
await p.waitForTimeout(1200);
if(await p.getByLabel("board password").count()){await p.getByLabel("board password").fill("board-test-pw");await p.getByRole("button",{name:"Sign in"}).click();}
await p.locator('[aria-label^="column "]').first().waitFor({timeout:15000});
await p.getByTestId("hire-open").click();
await p.waitForTimeout(600);
chk("role field present", (await p.getByLabel("persona prompt").count())>0);
await p.getByLabel("persona prompt").fill("Strict reviewer: flag every risk.");
chk("role field accepts text", (await p.getByLabel("persona prompt").inputValue()).includes("Strict"));
await p.keyboard.press("Escape");
await b.close();
console.log(`\nPERSONA: ${pass} passed, ${fail} failed`);
process.exit(fail?1:0);
